Fixed the system for icd-10 and return unknown if the icd-10 is empty
samply/report-hub pull request #5
Opened 2022-11-24 08:00 UTC by patrickskowronekdkfz

2022-11-24 09:28 UTC, lablans commented on src/main/resources/de/samply/reporthub/exliquid/Library-dashboard.cql
> +  if (retrieveCondition is null) then 'unkown' else retrieveCondition
```suggestion
  if (retrieveCondition is null) then 'unknown' else retrieveCondition
```

2022-11-24 09:33 UTC, alexanderkiel approved these changes

2022-11-24 09:37 UTC, alexanderkiel requested changes
Please rebase on main.

2022-11-25 14:13 UTC, alexanderkiel approved these changes

2022-11-25 14:15 UTC, merged